exclude:            ["README.md", ".git/", "Gemfile", "Gemfile.lock", ".gitignore", "LICENSE.txt"]
keep_files:         [".git"]
encoding:           "utf-8"
permalink:          pretty
theme:              minima
url:                https://riccibruno.github.io
description:        " "
title:              " "
author:             Bruno Ricci
show_excerpts:      false
minima:
    date_format:    "%e %B %Y"
header_pages:
    - about.md
plugins:
    - jekyll-feed
    - jekyll-seo-tag
