exclude:            ["README.md", ".git/", "Gemfile", "Gemfile.lock", ".gitignore", "LICENSE.txt", "about.md"]
keep_files:         [".git"]
encoding:           "utf-8"
permalink:          pretty
theme:              minima
url:                https://riccibruno.github.io
description:        " "
title:              "Bruno Ricci's blog"
author:             Bruno Ricci
show_excerpts:      true
timezone:           Europe/London
future:             true
paginate:           1
paginate_path:      "/page/:num/"
minima:
    date_format:    "%e %B %Y"
header_pages:
 - category_c++.html
plugins:
    - jekyll-seo-tag
    - jekyll-relative-links
    - jekyll-paginate
relative_links:
    enabled:     true
    collections: false
defaults:
    -
        scope:
            path:   ""
        values:
            author: Bruno Ricci
    -
        scope:
            path:       "_posts"
        values:
            layout:     "post"
            excerpt:    " "
